// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYQqL42GPf56T5hTovBSJ7T1R1AY3ucpE',
    appId: '1:264910741690:web:666741126369fa83eb2283',
    messagingSenderId: '264910741690',
    projectId: 'school-app-1db46',
    authDomain: 'school-app-1db46.firebaseapp.com',
    storageBucket: 'school-app-1db46.firebasestorage.app',
    measurementId: 'G-3JBJ6C44RP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRp6uVxTjWEgApCVyVxuJnVyoYc9A-RUg',
    appId: '1:264910741690:android:396cb6aeb5730f51eb2283',
    messagingSenderId: '264910741690',
    projectId: 'school-app-1db46',
    storageBucket: 'school-app-1db46.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfO59tSjiE9qGehdnuW8C4te8lElzQmHo',
    appId: '1:264910741690:ios:ecce937d0fe7fda0eb2283',
    messagingSenderId: '264910741690',
    projectId: 'school-app-1db46',
    storageBucket: 'school-app-1db46.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfO59tSjiE9qGehdnuW8C4te8lElzQmHo',
    appId: '1:264910741690:ios:ecce937d0fe7fda0eb2283',
    messagingSenderId: '264910741690',
    projectId: 'school-app-1db46',
    storageBucket: 'school-app-1db46.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYQqL42GPf56T5hTovBSJ7T1R1AY3ucpE',
    appId: '1:264910741690:web:b03729e6b55fb47beb2283',
    messagingSenderId: '264910741690',
    projectId: 'school-app-1db46',
    authDomain: 'school-app-1db46.firebaseapp.com',
    storageBucket: 'school-app-1db46.firebasestorage.app',
    measurementId: 'G-14JLNSLHQJ',
  );
}
